python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州景点_897/广州景点50下.json review tour >> ins.tour.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州景点_897/广州景点50上.json review tour >> ins.tour.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州餐厅_32105/广州餐厅50上.json review cater >> ins.cater.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州餐厅_32105/广州餐厅50下.json review cater >> ins.cater.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州酒店_4676/广州酒店50上.json review hotel >> ins.hotel.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州酒店_4676/广州酒店50下.json review hotel >> ins.hotel.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海酒店_7564/上海酒店50下.json review hotel >> ins.hotel.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海酒店_7564/上海酒店50上.json review hotel >> ins.hotel.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海餐厅_39849/上海餐厅50上.json review cater >> ins.cater.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海餐厅_39849/上海餐厅50下.json review cater >> ins.cater.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海景点_1782/上海景点50上.json review tour >> ins.tour.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海景点_1782/上海景点50下.json review tour >> ins.tour.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京酒店_8298/北京酒店50下.json review hotel >> ins.hotel.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京酒店_8298/北京酒店50上.json review hotel >> ins.hotel.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京景点_2043/北京景点50上.json review tour >> ins.tour.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京景点_2043/北京景点50下.json review tour >> ins.tour.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京餐厅_23794/北京餐厅50下.json review cater >> ins.cater.log
python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京餐厅_23794/北京餐厅50上.json review cater >> ins.cater.log

#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州景点_897/广州景点50下.json review guangzhou_tour >> ins.guangzhou_tour.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州景点_897/广州景点50上.json review guangzhou_tour >> ins.guangzhou_tour.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州餐厅_32105/广州餐厅50上.json review guangzhou_cater >> ins.guangzhou_cater.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州餐厅_32105/广州餐厅50下.json review guangzhou_cater >> ins.guangzhou_cater.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州酒店_4676/广州酒店50上.json review guangzhou_hotel >> ins.guangzhou_hotel.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/广州/广州酒店_4676/广州酒店50下.json review guangzhou_hotel >> ins.guangzhou_hotel.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海酒店_7564/上海酒店50下.json review shanghai_hotel >> ins.shanghai_hotel.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海酒店_7564/上海酒店50上.json review shanghai_hotel >> ins.shanghai_hotel.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海餐厅_39849/上海餐厅50上.json review shanghai_cater >> ins.shanghai_cater.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海餐厅_39849/上海餐厅50下.json review shanghai_cater >> ins.shanghai_cater.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海景点_1782/上海景点50上.json review shanghai_tour >> ins.shanghai_tour.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/上海/上海景点_1782/上海景点50下.json review shanghai_tour >> ins.shanghai_tour.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京酒店_8298/北京酒店50下.json review beijing_hotel >> ins.beijing_hotel.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京酒店_8298/北京酒店50上.json review beijing_hotel >> ins.beijing_hotel.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京景点_2043/北京景点50上.json review beijing_tour >> ins.beijing_tour.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京景点_2043/北京景点50下.json review beijing_tour >> ins.beijing_tour.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京餐厅_23794/北京餐厅50下.json review beijing_cater >> ins.beijing_cater.log
#python -m insert_db.curated_geokb /home/zxteloiv/datasets/评论信息用户信息/北京/北京餐厅_23794/北京餐厅50上.json review beijing_cater >> ins.beijing_cater.log
